### ISSUE TITLE
Issues of Refering to Microsoft.VisualStudio.Shell.15.0.dll

### ISSUE THREAD

**Issue by benZhai01** [microsoft/xaml-designer-extensibility#12]
Currently the DesignTools project has the dependency of `Microsoft.VisualStudio.Shell.15.0.dll` to support VS Theme. 
IIRC, each version of VisualStudio has the corresponding SDK which maybe inlcude the different `Microsoft.VisualStudio.Shell.<version>.dll`. 
So is there a possiblity that the `Microsoft.VisualStudio.Shell.<version>.dll` will be upgraded again in future Visual Studio? If so, how to make the same DesignTools work in both old and new Visual Studio?

**Comment by hemantbajpai4** [comment]
Yes there is possibility that Microsoft.VisualStudio.Shell.<version>.dll will be upgraded again but 15.0 version will be compatible with 16.0 and it is unclear if this will roll forward.

**Comment by benZhai01** [comment]
@hemantbajpai4 
thanks for detail, but this `unclear` would be a risk for us, right?

So let me explain more.

Now the designtools refers to `15.0.dll` to apply VS2019 theme, we assume that VS2020 would change UX(theme) a lot, and the `16.0.dll` appears. 
Then can the designtools whcih still refer to `15.0.dll` apply the correct VS theme in VS2020? or if want to make it works, we have to refer to `16.0.dll`?

**Comment by lutzroeder** [comment]
@jekelly

**Comment by benZhai01** [comment]
Any updates?
