### ISSUE TITLE
Custom control not display in Toolbox

### ISSUE THREAD

**Issue by Kannan1015** [microsoft/xaml-designer-extensibility#15]
Hi,

I followed the instruction to create the NuGet pack from your sample project, add the fallback config file, and fallback folder. Run the NuGet.exe tool to expand. But the custom toolbox is not visible in the WPF .NET Core application. 

I tried with Visual Studio 2019 version 16.6.

**Comment by debonte** [comment]
@Kannan1015 this feature is not supported in 16.6. You need 16.7 Preview 2 or later.

**Comment by Kannan1015** [comment]
Yes. It works.
