### ISSUE TITLE
Nuget package Microsoft.VisualStudio.DesignTools not available anywhere?

### ISSUE THREAD

**Issue by mterwoord** [microsoft/xaml-designer-extensibility#2]
Where can we find the Microsoft.VisualStudio.DesignTools nuget package?

**Comment by hemantbajpai4** [comment]
Thank you for reporting this. We are tracking this for a future update.

**Comment by mterwoord** [comment]
Also, with latest preview I cannot compile it. Any way to get going with it?

**Comment by hemantbajpai4** [comment]
Code should compile with 16.3 preview 2 which is releasing 8/13. You can comment the features which are causing errors or let me know the errors I can help.

**Comment by hemantbajpai4** [comment]
Fixed now.
