### ISSUE TITLE
Lightbulb in custom controls?

### ISSUE THREAD

**Issue by arivoir** [microsoft/xaml-designer-extensibility#20]
We are interested in showing the lightbulb popup in our controls, as it is present in MS controls

![image](https://user-images.githubusercontent.com/17496741/84532755-29e6a800-acbd-11ea-9404-32b5e21c4cec.png)

Is it possible? How are the properties appearing there specified?

**Comment by koljaka** [comment]
Currently our team is working on extensibility for "XAML Suggested Actions". We will keep you updated.

**Comment by arivoir** [comment]
Is this released? I updated nuget package Microsoft.VisualStudio.DesignTools.Extensibility to latest version 16.6.30107.105 and SuggestedActionProvider doesn't seem available

**Comment by koljaka** [comment]
This feature is available only in Preview Channel starting from 16.7 Preview 3. Please manually reference "Microsoft.VisualStudio.DesignTools.Extensibility.dll" and "Microsoft.VisualStudio.DesignTools.Interaction.dll" from "[VisualStudio_16.7_Preview3_install_folder]\Common7\IDE\PublicAssemblies"

**Comment by arivoir** [comment]
Will it be available in the nuget package soon?
