### ISSUE TITLE
2 attributes for enabling "Suggested Actions"

### ISSUE THREAD

**Issue by arivoir** [microsoft/xaml-designer-extensibility#24]
Why do we need to add 2 attributes to enable "Suggested Actions"

```
Builder.AddCustomAttributes("C1.WPF.Core.C1PathIcon", new SuggestionsAttribute());
Builder.AddCustomAttributes("C1.WPF.Core.C1PathIcon", new FeatureAttribute(typeof(C1PathIconSuggestedActionProvider)));
```

_DefaultInitializer_ seems an analogous feature that only needs one

`Builder.AddCustomAttributes("C1.WPF.Core.C1PathIcon", new FeatureAttribute(typeof(C1PathIconInitializer)));`

Why 2 attributes?

**Comment by arivoir** [comment]
Additionally, the control full type "C1.WPF.Core.C1PathIcon" needs to be specified twice 2.

When adding the attribute

`Builder.AddCustomAttributes("C1.WPF.Core.C1PathIcon", new FeatureAttribute(typeof(C1PathIconSuggestedActionProvider)));`

And in the SuggestedActionProvider class

```
public class C1PathIconSuggestedActionProvider : SuggestedActionProvider
{
    public override string Type => "C1.WPF.Core.C1PathIcon";
}

```
What is the reason to having to specify this twice?
The DefaultInitializer api looks much cleaner, only one attribute, and it doesn't need to report its "Type"

**Comment by thsparks** [comment]
Hi. Thanks for bringing this to our attention. In the latest preview, you should no longer have to register a separate SuggestionsAttribute (see updated documentation here: [metadata registration](https://github.com/microsoft/xaml-designer-extensibility/blob/main/documents/xaml-suggested-actions/xaml-designer-suggested-actions-extensibility.md#metadata-registration)), and we have removed the Type field.
